/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/avatar/avatar-rodrigo.glb -t 
*/

import { ARKIT_ORDER_61 } from '@convai/web-sdk/lipsync-helpers';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import React, { useRef, useEffect } from 'react';
import * as THREE from 'three';
import { SkeletonUtils } from 'three-stdlib';

import { useConvaiStore } from '../runtime/convai/useConvaiStore';

import type { ThreeElements } from '@react-three/fiber';
import type { GLTF } from 'three-stdlib';

type ActionName = 'AvatarWeb_CC5_v1|Default';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  animations: GLTFAction[];
}

const arkitToGlbMap = {
  eyeBlinkLeft: 'Eye_Blink_L',
  eyeLookDownLeft: 'Eye_L_Look_Down',
  eyeLookInLeft: 'Eye_L_Look_R',
  eyeLookOutLeft: 'Eye_L_Look_L',
  eyeLookUpLeft: 'Eye_L_Look_Up',
  eyeSquintLeft: 'Eye_Squint_L',
  eyeWideLeft: 'Eye_Wide_L',
  eyeBlinkRight: 'Eye_Blink_R',
  eyeLookDownRight: 'Eye_R_Look_Down',
  eyeLookInRight: 'Eye_R_Look_L',
  eyeLookOutRight: 'Eye_R_Look_R',
  eyeLookUpRight: 'Eye_R_Look_Up',
  eyeSquintRight: 'Eye_Squint_R',
  eyeWideRight: 'Eye_Wide_R',
  jawForward: 'Jaw_Forward',
  jawLeft: 'Jaw_L',
  jawRight: 'Jaw_R',
  jawOpen: 'Jaw_Open',
  mouthClose: 'Mouth_Close',
  mouthFunnel: 'Mouth_Funnel',
  mouthPucker: 'Mouth_Pucker',
  mouthLeft: 'Mouth_L',
  mouthRight: 'Mouth_R',
  mouthSmileLeft: 'Mouth_Smile_L',
  mouthSmileRight: 'Mouth_Smile_R',
  mouthFrownLeft: 'Mouth_Frown_L',
  mouthFrownRight: 'Mouth_Frown_R',
  mouthDimpleLeft: 'Mouth_Dimple_L',
  mouthDimpleRight: 'Mouth_Dimple_R',
  mouthStretchLeft: 'Mouth_Stretch_L',
  mouthStretchRight: 'Mouth_Stretch_R',
  mouthRollLower: 'Mouth_Roll_In_Lower',
  mouthRollUpper: 'Mouth_Roll_In_Upper',
  mouthShrugLower: 'Mouth_Shrug_Lower',
  mouthShrugUpper: 'Mouth_Shrug_Upper',
  mouthPressLeft: 'Mouth_Press_L',
  mouthPressRight: 'Mouth_Press_R',
  mouthLowerDownLeft: 'Mouth_Down_Lower_L',
  mouthLowerDownRight: 'Mouth_Down_Lower_R',
  mouthUpperUpLeft: 'Mouth_Up_Upper_L',
  mouthUpperUpRight: 'Mouth_Up_Upper_R',
  browDownLeft: 'Brow_Drop_L',
  browDownRight: 'Brow_Drop_R',
  browOuterUpLeft: 'Brow_Raise_Outer_L',
  browOuterUpRight: 'Brow_Raise_Outer_R',
  cheekSquintLeft: 'Cheek_Raise_L',
  cheekSquintRight: 'Cheek_Raise_R',
  noseSneerLeft: 'Nose_Sneer_L',
  noseSneerRight: 'Nose_Sneer_R',
  browInnerUp: ['Brow_Raise_Inner_L', 'Brow_Raise_Inner_R'],
  cheekPuff: ['Cheek_Puff_L', 'Cheek_Puff_R'],
  tongueOut: ['Tongue_Bulge_L', 'Tongue_Bulge_R']
};

const AVATAR_URL = `${import.meta.env.BASE_URL}avatar/avatar-rodrigo.glb`;
const ANIMATION_URL = `${import.meta.env.BASE_URL}avatar/animation.glb`;

export function Model(props: ThreeElements['group']) {
  const group = useRef<THREE.Group>(null);

  const { scene } = useGLTF(AVATAR_URL) as unknown as GLTFResult;
  const { animations: extraAnimations } = useGLTF(ANIMATION_URL);
  
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { actions } = useAnimations(extraAnimations, group);
  
  const currentAnimation = useRef('Idle');
  
  const lipsyncStartTime = useRef<number | null>(null);
  const speechTimeout = useRef(0);
  const lipsyncEnv = useRef(0); 
  const lastFrame = useRef<Float32Array | null>(null);

  const morphMeshes = useRef<THREE.Mesh[]>([]);
  const jawBone = useRef<THREE.Bone | null>(null);

  useEffect(() => {
    const meshes: THREE.Mesh[] = [];
    let bone: THREE.Bone | null = null;
    
    clone.traverse((child) => {
      const node = child as THREE.Object3D & {
        isMesh?: boolean;
        isSkinnedMesh?: boolean;
        isBone?: boolean;
        morphTargetDictionary?: { [key: string]: number };
        morphTargetInfluences?: number[];
      };
      
      if (node.isMesh || node.isSkinnedMesh) {
        node.frustumCulled = false;
        if (node.morphTargetDictionary && node.morphTargetInfluences) {
          meshes.push(node as THREE.Mesh);
        }
      }

      if (node.isBone && node.name === 'CC_Base_Teeth02') {
        bone = node as THREE.Bone;
      }
    });

    morphMeshes.current = meshes;
    jawBone.current = bone;
  }, [clone]);

  useEffect(() => {
    if (!actions) return;
    
    extraAnimations.forEach((clip) => {
      clip.tracks = clip.tracks.filter(
        (track) => !track.name.includes('morphTargetInfluences')
      );
    });

    const availableNames = Object.keys(actions);
    const animName = actions['Idle'] ? 'Idle' : availableNames[0];
    
    if (animName && actions[animName]) {
      actions[animName].reset().fadeIn(0.5).play();
      currentAnimation.current = animName;
    }
  }, [actions, extraAnimations]);

  useFrame((_, delta) => {
    const client = useConvaiStore.getState().client;

    if (!client || !client.blendshapeQueue) return;
    
    const queue = client.blendshapeQueue;
    let targetJawOpen = 0; 

    if (queue.isBotSpeaking()) {
      if (lipsyncStartTime.current === null) {
        lipsyncStartTime.current = performance.now();
      }

      const elapsed = (performance.now() - lipsyncStartTime.current) / 1000;
      const result = queue.getFrameAtTime(elapsed);

      if (result) {
        lastFrame.current = new Float32Array(result.frame);
      }
      
      speechTimeout.current = 0.3; 
    } else {
      lipsyncStartTime.current = null;
      if (speechTimeout.current > 0) {
        speechTimeout.current -= delta;
      }
    }

    const isCharacterTalking = speechTimeout.current > 0;

    const targetEnv = isCharacterTalking ? 1 : 0;
    const tau = targetEnv > lipsyncEnv.current ? 0.09 : 0.18;
    lipsyncEnv.current += (targetEnv - lipsyncEnv.current) * (1 - Math.exp(-delta / tau));

    if (lastFrame.current && lipsyncEnv.current > 0.001) {
      const frameData = new Float32Array(lastFrame.current);

      for (let i = 0; i < ARKIT_ORDER_61.length; i++) {
        const name = ARKIT_ORDER_61[i];
        if (name.endsWith('Left')) {
          const rightName = name.replace('Left', 'Right');
          const rightIndex = ARKIT_ORDER_61.indexOf(rightName as (typeof ARKIT_ORDER_61)[number]);
          if (rightIndex !== -1) {
            const avg = (frameData[i] + frameData[rightIndex]) / 2;
            frameData[i] = avg;
            frameData[rightIndex] = avg;
          }
        }
      }

      morphMeshes.current.forEach((mesh) => {
        const dict = mesh.morphTargetDictionary!;
        const influences = mesh.morphTargetInfluences!;

        ARKIT_ORDER_61.forEach((arkitName, i) => {
          const normalizedKey = arkitName.charAt(0).toLowerCase() + arkitName.slice(1);
          const glbTarget = arkitToGlbMap[normalizedKey as keyof typeof arkitToGlbMap];
          
          let val = frameData[i] || 0; 

          if (normalizedKey === 'jawOpen') val *= 0.6; 
          if (normalizedKey === 'jawLeft' || normalizedKey === 'jawRight') val *= 0.0; 
          if (normalizedKey === 'mouthLeft' || normalizedKey === 'mouthRight') val *= 0.0; 

          val *= lipsyncEnv.current; 

          if (normalizedKey === 'jawOpen') targetJawOpen = val;

          if (glbTarget) {
            if (Array.isArray(glbTarget)) {            
              glbTarget.forEach(target => {
                const index = dict[target]; 
                if (index !== undefined) influences[index] = val; 
              });
            } else {
              const index = dict[glbTarget]; 
              if (index !== undefined) influences[index] = val; 
            }
          }
        }); 
      });
    } else if (lipsyncEnv.current <= 0.001) {
      lastFrame.current = null;
      morphMeshes.current.forEach((mesh) => {
        const dict = mesh.morphTargetDictionary!;
        const influences = mesh.morphTargetInfluences!;
        Object.values(arkitToGlbMap).flat().forEach(target => {
          const index = dict[target];
          if (index !== undefined) {
            influences[index] = THREE.MathUtils.lerp(influences[index], 0, 0.2);
          }
        });
      });
    }

    if (jawBone.current) {
      jawBone.current.rotation.x = THREE.MathUtils.lerp(
        jawBone.current.rotation.x, 
        targetJawOpen * 0.25, 
        0.4
      );
    }

    let targetAnimation = 'Idle';
    if (isCharacterTalking && actions['Talk']) {
        targetAnimation = 'Talk';    
    } else if (!actions['Idle']) {
        targetAnimation = Object.keys(actions)[0] || 'Idle'; 
    }

    if (currentAnimation.current !== targetAnimation && actions[targetAnimation]) {
      const prevAction = actions[currentAnimation.current];
      const nextAction = actions[targetAnimation];

      if (prevAction) prevAction.fadeOut(0.3); 
      if (nextAction) nextAction.reset().fadeIn(0.3).play(); 
      
      currentAnimation.current = targetAnimation;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  );
}

useGLTF.preload(AVATAR_URL);
useGLTF.preload(ANIMATION_URL);